name: flutter_restaurant
description: A new Flutter restaurant application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  get_it: ^7.2.0
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  dio: ^5.0.1
  image_picker: ^0.8.5+3
  pin_code_fields: ^7.4.0
  google_maps_flutter: ^2.1.12
  geocoding: ^2.0.5
  geolocator: ^9.0.1
  shimmer: ^2.0.0
  url_launcher: ^6.1.5
  webview_flutter: ^4.0.6
  firebase_core: ^2.7.1
  firebase_messaging: ^14.2.6
  flutter_local_notifications: ^13.0.0
  path_provider: ^2.0.11
  flutter_html: ^3.0.0-alpha.6
  connectivity: ^3.0.6

dev_dependencies:
  flutter_launcher_icons: ^0.12.0
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/image_icon.png"
  min_sdk_android: 21
  color: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/
    - assets/language/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700